/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, BackHandler } from 'react-native';

import Backstage from 'react-native-backstage';

export default class App extends Component {
	state = {
		status: 'starting',
		message: '--'
	};
	componentDidMount() {
		BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
	}

	componentWillUnmount() {
		BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
	}

	onBackPress = () => {
		return false;
	};
	render() {
		return (
			<View style={styles.container}>
				<Text
					onPress={() => {
						this.setState({
							status: '99999'
						});
					}}
					style={styles.welcome}
				>
					☆RNBackstage example☆
				</Text>
				<Text style={styles.instructions}>STATUS: {this.state.status}</Text>
				<Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
				<Text style={styles.instructions}>{this.state.message}</Text>
			</View>
		);
	}
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#F5FCFF'
	},
	welcome: {
		fontSize: 20,
		textAlign: 'center',
		margin: 10
	},
	instructions: {
		textAlign: 'center',
		color: '#333333',
		marginBottom: 5
	}
});
